### ISSUE TITLE
Cannot find 0.0.7 Version 

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [michael-simons/wro4j-spring-boot-starter#1]
I'm trying to use your starter but i am unable to get your jars neither from maven nor from repositories you have added in pom.

**Comment by michael-simons** [comment]
Weird. They're all there http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22eu.michael-simons%22%20AND%20a%3A%22wro4j-spring-boot-starter%22. 

Current released version is 0.0.10 which is in central. You won't have to add any repos.  Current code is prepared for Spring Boot 1.4 release, so the Pom here is containing currently the Spring Snapshot repos.

**Comment by rajjaiswalsaumya** [comment]
Is Current released version is 0.0.10  that upgraded to boot 1.4.0.M3 ? 
Because FilterRegistration package is moved from **context to **web ?

**Comment by rajjaiswalsaumya** [comment]
I just checked, it didn't. So, in my case I cant go with 0.0.10 because I m using 1.4.0.M3 boot parent.

**Comment by michael-simons** [comment]
Nope, that won't work with 1.4.0. It's for 1.3.x. I'll release a new version as soon as Spring Boot 1.4 is released. 

But you should be able to build it yourself and use the snapshot for the time being. 1.4 should be available in August I guess.

**Comment by michael-simons** [comment]
I'm actually using a snapshot from the code as it is today in one of my projects. All tests are green. If it helps I'll send you a jar.

**Comment by rajjaiswalsaumya** [comment]
Not an issue, I thought that is released. Anyway building myself. Thanks anyway :)

**Comment by rajjaiswalsaumya** [comment]
Just a suggestion please add nbactions.xml and nb-configuration.xml to your .gitignore. They are IDE specific files and should not be added to repositories.

**Comment by rajjaiswalsaumya** [comment]
Build fails 

6-07-04 02:20:09.693  INFO 7756 --- [       Thread-4] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@38682845: startup date [Mon Jul 04 02:20:07 IST 2016]; root of context hierarchy

Results :

Failed tests:
  RemoveSourceMapsProcessorTest.processShouldWork:51 expected:<normal[
 blanks am anfang und ende
Javascript Single line
Javascript Multi line
CSS Multi line
Depecrated formats
ende]
> but was:<normal[
 blanks am anfang und ende
Javascript Single line
Javascript Multi line
CSS Multi line
Depecrated formats
]nde
>

**Comment by michael-simons** [comment]
Can you tell me OS and JVM version as well as language settings? I'll fix that.

**Comment by michael-simons** [comment]
I've fixed the build (see GH-2) and have attached [wro4j-spring-boot-starter-0.0.11-SNAPSHOT.zip](https://github.com/michael-simons/wro4j-spring-boot-starter/files/345754/wro4j-spring-boot-starter-0.0.11-SNAPSHOT.zip) for your convenience.

Regarding the NetBeans files: They are there to stay, I like it that way because I use several machines to develop and want the settings to be shared. Thanks.
