### ISSUE TITLE
WroRuntimeException: No locator is capable of handling uri

### ISSUE THREAD

**Issue by yosamaru** [michael-simons/wro4j-spring-boot-starter#19]
`<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro">
  <group name="angular">
    <js>webjar:angular.min.js</js>
    <js>webjar:angular-route.min.js</js>
    <js>webjar:angular-ui-router.min.js</js>
  </group>

  <group name="std">
    <group-ref>angular</group-ref>
    <js>classpath*:/app/system/service.js</js>
    <js>classpath*:/app/system/service-*.js</js>
    <js>classpath:/app/std/**/*.js</js>
  </group>
</groups>
`
Above is my wro.xml.
run exception: ro.isdc.wro.WroRuntimeException: No locator is capable of handling uri: classpath*:/app/system/service.js

this is why?
thank you !

**Comment by michael-simons** [comment]
I cannot tell from the information you give. Would you mind providing something formatted and an actual stack trace? Thank you.

**Comment by yosamaru** [comment]
Thank you, I  find reason, I not import wro4j-extensions 。
