### ISSUE TITLE
How do you control the order of web filter chain?

### ISSUE THREAD

**Issue by chubbard** [michael-simons/wro4j-spring-boot-starter#192]
Hi,

I'm trying to use the wro4j-spring-boot-starter with Spring Security and I need to control the order of the filters on the ServletContext's web filter chain.  I need The WroFilter to be before Spring Security.  Is there a way to control the order of the WroFilter through the configuration parameters or through another mechanism?

**Comment by michael-simons** [comment]
Hej @chubbard Not yet at the moment. I could however add a customiser for the `FilterRegistrationBean<ConfigurableWroFilter>` so that you can set the order there. Would that work for you?

**Comment by michael-simons** [comment]
Or better, I'd rather add a condition on the autoconfig and a name to the bean, so that you can overwrite it…

**Comment by michael-simons** [comment]
That was easy enough to add, see readme and the test… Will release this soon.

**Comment by chubbard** [comment]
Awesome Michael!  Can't wait to test it out.  I barely read your reply before you finished it. 🥇
