### ISSUE TITLE
Having trouble adding a custom processor

### ISSUE THREAD

**Issue by srgibbs99** [michael-simons/wro4j-spring-boot-starter#3]
I tried adding "wro4j.managerFactoryClassName" along with my other wro4j properties, but I'm not seeing my factory class being used.
Can you recommend the best way to add a custom processor using this starter?

**Comment by michael-simons** [comment]
Hi! 

Did you check how it's done with the additional `RemoveSourceMapsProcessor` I provide?

In your applications `src/main/resources` create a META-INF folder containing the folder `services` like you see here https://github.com/michael-simons/wro4j-spring-boot-starter/tree/master/src/main/resources/META-INF/services. 

Inside this folder create a file named exactly `ro.isdc.wro.model.resource.processor.support.ProcessorProvider` which contains one line with the fully qualified name of your processor provider as you see in the example.

This provider should look similar to https://github.com/michael-simons/wro4j-spring-boot-starter/blob/master/src/main/java/ac/simons/spring/boot/wro4j/processors/Wro4jProcessorProvider.java, notice in line 40 how the names of the processors are declared? Do the same for your processor.

Then you can use `wro4j.managerFactory.preProcessors = removeSourceMaps`.

This is not specific to this starter, this is the way wro4j makes the processor available with the Java service locator.

Another option is to use the property `wro4j.preProcessors` (See the difference? Omit the managerFactory). This one takes the full qualified class name of the processor you wish to use and you can omit the processor provider.

Let me know if this works for you. If not, please send me some code, I'll have a look.

**Comment by srgibbs99** [comment]
Nice!  I got it working using the first method. (Created a Provider, registered it using the file in META-INF, specified the key/alias in my property file).  I tried the second option, but it seemed to conflict if I had other processors specified using the "`wro4j.managerFactory.preProcessors`" syntax.  Only one or the other would apply.

I was hoping to use a "spring-boot" way of doing this, and use a Managed Bean for my preProcessor, but I'm not sure how to do what.  I assume WRO locates my processor and instantiates it.  Is there a way to provide WRO my bean from the spring application context instead? (just thought of maybe using the singleton pattern in my bean).

My end goal is create a "Placeholder" processor that will use properties from `applicaton.properties` and replace them in my JS/CSS files.  Currently I am extending from the `PlaceholderProcessor` impl provided in core WRO. I could create a new set of properties just for this, but i would prefer to inject a `ConfigurationProperties` or just the spring `Environment` and use any properties I find from there.

Any ideas/suggestions are appreciated.

Thanks for the help. I love this starter, The WRO people need to adopt it :)

**Comment by michael-simons** [comment]
Thanks for the feedback. 

First: true! Those options are mutual exclusive. Either you specify the classes directly or configure the factory. That's because the detection of processors by name is done using a different wro processor factory then the one that supports setting them by class. 

That being said, I could think of a way to provide bean names so that you can configure a bean of your own. 

But: the wro4j processor factory will be exposed as a bean, see https://github.com/michael-simons/wro4j-spring-boot-starter/blob/master/src/main/java/ac/simons/spring/boot/wro4j/Wro4jAutoConfiguration.java#L89
If you don't configure processors or use the name method, you'll get a 
https://github.com/wro4j/wro4j/blob/1.8.x/wro4j-core/src/main/java/ro/isdc/wro/model/resource/processor/factory/SimpleProcessorsFactory.java

Try the following: let spring inject this into you config and add your processor bean. Maybe wro4j itself still takes the processor into account even if at this point, the wro filter and manager is alread defined.

**Comment by srgibbs99** [comment]
I tried injecting the bean you mentioned and adding my preProcessor, but no luck, Wro seemed to ignore it at that point.  I tried a couple of other ways to inject the manager, but no luck.  Maybe if the ManagerFactory was a `ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory` I might be able to use the "contributePreProcessors" method.  But it seems the instance in the Spring Context is just a "BaseWroManagerFactory". But maybe even then it would be too late if the manager was already created.

I just went back to using the Option 1 method from above and manually load the properties I need for replacement.  It works well, but I'm always looking for the "spring-boot" way of doing things.

Feel free to close this issue, if you like, or if you have any more ideas I am open to them.

Thanks again!

**Comment by michael-simons** [comment]
Thank you for your feedback on the starter! I'm close this but keep it in mind to add this as a feature.

**Comment by michael-simons** [comment]
Hey,
a quick info: I've just released 0.2.1 which should help you greatly, see updated readme: https://github.com/michael-simons/wro4j-spring-boot-starter#configuration-of-pre--and-postprocessors

**Comment by michael-simons** [comment]
@srgibbs99 Did you had a chance to test this?

**Comment by srgibbs99** [comment]
@michael-simons This looks great, i will check it out.  One concern I have, though, is how to specify other pre-processors in conjunction with my own.  For example, in my case I am using two of wro4j built-in processors by specifying their alias, and also registering my own.  Maybe i could find their actual class names and create Spring @Bean methods that return instances of those also and then use this new method for all three?
