### ISSUE TITLE
Thymeleaf demo

### ISSUE THREAD

**Issue by kryzalid87** [michael-simons/wro4j-spring-boot-starter#6]
Hi, can you provide us a, simplest as it can, application demo using Thymeleaf - merging and minifying two CSS or JS files. I was looking on project provided by you on the bottom, but I have always problems and ends with not working version.
Thank a lot for any help :)

**Comment by michael-simons** [comment]
Hi.
See attachment: [wro4jdemo.zip](https://github.com/michael-simons/wro4j-spring-boot-starter/files/901848/wro4jdemo.zip). Unzip and run with `mvn spring-boot:run` and goto [http://localhost:8080](http://localhost:8080). You'll see pink on black, coming from 2 css sheets that are concatenated and minified with 

```xml
<?xml version="1.0" encoding="UTF-8"?>

<groups xmlns="http://www.isdc.ro/wro">
    <group name="demo">
	
	<css>/style1.css</css>
	<css>/style2.css</css>
    </group>    
</groups>
```

Pretty straight forward, I hope.

**Comment by kryzalid87** [comment]
Thank you very much. Now all makes more sens. Was trying for ages to make it work, and now see that I had issue in xml file. Noob problem
