### ISSUE TITLE
Wild card issue with relative path

### ISSUE THREAD

**Issue by gcoulon** [michael-simons/wro4j-spring-boot-starter#8]
Hi,

It seams that the wild card feature doesn't work for a relative path in the version 0.3.4.

Kind regards

Grégory

**Comment by michael-simons** [comment]
Can you provide an example? Including expected behavior please?

**Comment by gcoulon** [comment]
Any wild card declaration give me this error:
<js>/assets/moment/*.js</js>
2017-06-08 14:24:56.606 ERROR 7512 --- [nio-8080-exec-3] r.i.w.m.g.p.PreProcessorExecutor         : Cannot ignore missing resource:  ro.isdc.wro.model.resource.Resource@c4459b[JS,/assets/moment/*.js,true]
2017-06-08 14:24:56.606 ERROR 7512 --- [nio-8080-exec-3] ro.isdc.wro.WroRuntimeException          : Exception while merging resources: Exception while reading resource from /assets/moment/*.js

But I try with manual confugration of Wro4j and I have the same problem, I think is due to Springboot Resource handler behavior.

Could you give me a workaround to avoid this behavior?

Thanks in advance

Grégory

**Comment by michael-simons** [comment]
I'll see what I can come up with…

**Comment by michael-simons** [comment]
I'm not sure that Springs resource handle is able to handle a wild card request. So you would come up with one of your one.

Another way would be not using root-relative URLS in your wro4j configuration but wildcards to classpath resources like this: `classpath:com/resources/*.css`, see: http://wro4j.readthedocs.io/en/stable/WildcardSupport/

**Comment by gcoulon** [comment]
Thanks for your response.
